##### Modfifications #####

# Dnm1 preprint
- id: doi:10.1101/2024.02.14.580336
  image: images/nucleophagy.png
  publisher: bioRxiv
  tags:
    - research article 

#ESCRT grommet
- id: doi:10.1038/s41556-023-01235-4
  image: https://media.springernature.com/full/springer-static/esm/art%3A10.1038%2Fs41556-023-01235-4/MediaObjects/41556_2023_1235_Fig13_ESM.jpg?as=webp
  tags:
    - research article 

- id: doi:10.1523/jneurosci.2525-16.2016
  title: Seeking an _In Vivo_ Neuronal Context for the PINK1/Parkin Pathway
  tags:
    - commentary

##### Remove old preprints #####
  
#ESCRT grommet
- id: doi:10.1101/2022.12.12.520126
  remove: true

#atg39 first paper
- id: doi:10.1101/2021.02.22.432332
  remove: true

# bax
- id: doi:10.1101/382432
  remove: true 
